services:
  postgres:
    image: postgres:14-alpine
    container_name: "${POSTGRES_CONTAINER}"
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pg_data_14:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 2s
      timeout: 2s
      retries: 3

  api:
    container_name: "${API_CONTAINER}"
    restart: always
    build:
      dockerfile: Dockerfile
    ports:
      - "3030:${APP_PORT}"
    env_file:
      - .env
    environment:
      NODE_ENV: development
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}?schema=public"
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pg_data_14: {}

networks:
  app-network:
    driver: bridge