services:

  postgres:
    image: postgres:14-alpine
    container_name: ${POSTGRES_CONTAINER}
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  api:
    container_name: ${API_CONTAINER}
    restart: always
    build:
      dockerfile: Dockerfile
    ports:
      - "3030:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public"
    depends_on:
      - postgres

volumes:
  pg_data: { }