services:

  postgres:
    image: postgres:15
    container_name: ${POSTGRES_CONTAINER}
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  api:
    container_name: ${API_CONTAINER}
    restart: always
    build:
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:3000"
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  pg_data: { }